import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:ripple/core/models/comment_model.dart';
import 'package:ripple/core/models/post_model.dart';

class PostRepository {
  final FirebaseFirestore _firestore;

  PostRepository({FirebaseFirestore? firestore})
    : _firestore = firestore ?? FirebaseFirestore.instance;

  Future<void> addPost({
    required String userId,
    required String username,
    required String userProfilePic,
    String? text,
    String? imageUrl,
  }) async {
    final postRef = _firestore.collection('posts').doc();

    final newPost = PostModel(
      postId: postRef.id,
      userId: userId,
      username: username,
      userProfilePic: userProfilePic,
      timestamp: Timestamp.now(),
      text: text,
      imageUrl: imageUrl,
      likes: [],
      comments: [],
    );

    await postRef.set(newPost.toMap());
  }

  Stream<List<PostModel>> getPosts() {
    return _firestore
        .collection('posts')
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map(
          (snapshot) => snapshot.docs
              .map((doc) => PostModel.fromMap(doc.data(), doc.id))
              .toList(),
        );
  }

  Stream<PostModel> getPostStream(String postId) {
    return _firestore
        .collection('posts')
        .doc(postId)
        .snapshots()
        .map((doc) => PostModel.fromMap(doc.data()!, doc.id));
  }

  Stream<List<PostModel>> getUserPosts(String userId) {
    return _firestore
        .collection('posts')
        .where('userId', isEqualTo: userId)
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map(
          (snapshot) => snapshot.docs
              .map((doc) => PostModel.fromMap(doc.data(), doc.id))
              .toList(),
        );
  }

  Future<void> toggleLike({
    required String postId,
    required String currentUserId,
    required List<String> likes,
  }) async {
    final postRef = _firestore.collection('posts').doc(postId);

    if (likes.contains(currentUserId)) {
      await postRef.update({
        'likes': FieldValue.arrayRemove([currentUserId]),
      });
    } else {
      await postRef.update({
        'likes': FieldValue.arrayUnion([currentUserId]),
      });
    }
  }

  Future<void> addComment({
    required String postId,
    required String userId,
    required String username,
    required String userProfilePic,
    required String text,
  }) async {
    final comment = CommentModel(
      commentId: '', // It will be generated by Firestore
      userId: userId,
      username: username,
      userProfilePic: userProfilePic,
      text: text,
      timestamp: Timestamp.now(),
    );

    await _firestore.collection('posts').doc(postId).update({
      'comments': FieldValue.arrayUnion([comment.toMap()]),
    });
  }

  Future<void> updateUserPosts({
    required String userId,
    required String username,
    required String userProfilePic,
  }) async {
    final posts = await _firestore
        .collection('posts')
        .where('userId', isEqualTo: userId)
        .get();
    final batch = _firestore.batch();
    for (final doc in posts.docs) {
      batch.update(doc.reference, {
        'username': username,
        'userProfilePic': userProfilePic,
      });
    }
    await batch.commit();
  }

  Future<void> updatePost({
    required String postId,
    required String text,
    String? imageUrl,
  }) async {
    await _firestore.collection('posts').doc(postId).update({
      'text': text,
      'imageUrl': imageUrl,
    });
  }

  Future<void> deletePost(String postId) async {
    await _firestore.collection('posts').doc(postId).delete();
  }
}
